jobs:
  test_secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Output Secrets
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          # Add other Secrets here
        run: |
          echo "DATABASE_URL: $DATABASE_URL"
          echo "NEXTAUTH_SECRET: $NEXTAUTH_SECRET"
          # Add other Secrets here
